# Lua config for the Hyprland greeter session (greetd + sysc-greet).
#
# Pure-Lua replacement for the hyprlang `hyprland-greeter-config.conf`
# previously shipped inside the sysc-greet package. Generating it here keeps
# every Hyprland config in this repo on the Lua syntax and pins the exact
# sysc-greet/kitty/hyprctl store paths instead of inheriting sysc-greet's.
#
# Called with `pkgs.callPackage`, e.g.:
#   pkgs.callPackage ./hyprland-greeter-config.nix {
#     syscGreetPackage = inputs.sysc-greet.packages.${system}.default;
#     kittyPackage = pkgs.kitty;
#     kittyConf = "${syscGreetPackage}/etc/greetd/kitty.conf";
#   }
{
  lib,
  syscGreetPackage,
  kittyPackage,
  hyprlandPackage,
  kittyConf,
}:
let
  luaStr = lib.generators.toLua { };

  syscGreetBin = "${syscGreetPackage}/bin/sysc-greet";
  kittyBin = "${kittyPackage}/bin/kitty";
  hyprctlBin = "${hyprlandPackage}/bin/hyprctl";
in
''
  -- Greeter session for greetd + sysc-greet. Generated by Nix; do not edit.

  hl.config({
    -- No animations for faster greeter startup.
    animations = { enabled = false },

    -- Minimal decorations.
    decoration = {
      rounding = 0,
      blur = { enabled = false },
    },

    -- Greeter doesn't need gaps.
    general = {
      gaps_in = 0,
      gaps_out = 0,
      border_size = 0,
    },

    -- Disable Hyprland wallpaper/logo for greeter. The watchdog warning is
    -- off because greetd doesn't pass fd properly to start-hyprland.
    misc = {
      disable_hyprland_logo = true,
      disable_splash_rendering = true,
      background_color = "rgb(000000)",
      disable_watchdog_warning = true,
    },

    -- Suppress annoying update/donation popups.
    ecosystem = {
      no_update_news = true,
      no_donation_nag = true,
    },

    input = {
      kb_layout = "us",
      repeat_delay = 400,
      repeat_rate = 40,

      touchpad = {
        tap_to_click = true,
      },
    },
  })

  -- Fullscreen, opaque terminal for the greeter.
  hl.window_rule({
    fullscreen = true,
    opacity = "1.0",
    match = { class = "^(kitty)$" },
  })

  -- Layer rules for wallpaper daemon.
  hl.layer_rule({
    blur = true,
    match = { namespace = "wallpaper" },
  })

  -- Old `exec-once`: start sysc-greet's wallpaper daemon, then the greeter
  -- terminal, exiting Hyprland when the greeter quits.
  hl.on("hyprland.start", function()
    hl.exec_cmd(${luaStr "HOME=/var/lib/greeter ${syscGreetBin} --wallpaper-daemon"})
    hl.exec_cmd(${luaStr "XDG_CACHE_HOME=/tmp/greeter-cache HOME=/var/lib/greeter ${kittyBin} --start-as=fullscreen --config=${kittyConf} ${syscGreetBin} && ${hyprctlBin} dispatch exit"})
  end)
''
