#+title: Nix-config commands (Org Babel)
#+subtitle: Run maintenance commands here (TRAMP-ready)
#+PROPERTY: header-args :results output drawer

This document defines the repository's maintenance commands as runnable
Org Babel blocks.

** Usage
Execute blocks with =C-c C-c= (org-babel-execute-src-block) in Emacs.
TRAMP-ready blocks support remote execution over SSH with sudo elevation.

* switch
Rebuild and activate NixOS configurations locally or remotely.
** local
#+name: rebuild-local
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :async :results raw output drawer
nixos-rebuild switch --flake .#$(hostname) 2>&1
#+end_src

#+RESULTS: rebuild-local
:results:
warning: Git tree '/home/arthur/nix-config' has uncommitted changes
building the system configuration...
warning: Git tree '/home/arthur/nix-config' has uncommitted changes
activating the configuration...
setting up /etc...
reloading user units for arthur...
restarting sysinit-reactivation.target
the following new units were started: NetworkManager-dispatcher.service
Done. The new configuration is /nix/store/4kaqway672f98vzcqnglns6rn8kprg44-nixos-system-gmktec-k11-25.11.20251108.b6a8526
:end:

** remote
#+name: select-host
#+begin_src elisp :results value
(completing-read "Select a host" '("x220-nixos" "gmktec-k11"))
#+end_src

#+name: rebuild-remote
#+begin_src elisp :dir /sshx:gmktec-k11.lan:/home/arthur/nix-config/ :var targethost=select-host
  (async-shell-command
   (format "NIX_SSHOPTS=\"-C\" nixos-rebuild switch --flake .#%s --target-host %s --ask-sudo-password" targethost targethost))
#+end_src

* update flake
Update flake inputs to their latest versions.

** Update only the doom-config flake
#+name: update-doom-cmd
#+begin_src sh :detached t
nix flake update doom-config
#+end_src

** Update all flakes
#+name: update-cmd
#+begin_src sh :detached t
nix flake update
#+end_src

* Garbage collect
Remove Nix store items older than 1 day, locally or on selected host.
#+name: gc-remote
#+begin_src elisp :var targethost=select-host
(let* ((current-host (system-name))
       (tramp-path (if (string= targethost current-host)
                       "/sudo::~/"
                     (format "/sshx:%s|sudo:%s:~/" targethost targethost))))
  (let ((default-directory tramp-path))
    (async-shell-command "nix-collect-garbage --delete-older-than 1d")))
#+end_src
* Install when a random live ISO is booted
